apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-staging
  namespace: pesbuktest1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pesbuk-staging
  template:
    metadata:
      labels:
        name: pesbuk-staging
    spec:
      containers:
        - name: pesbuk-staging
          image: indraraspati/pesbuk-with-secret:pertama
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysecret1
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysecret1
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysecret1
                  key: DB_PASS
